openapi: 3.0.0
info:
  title: Example API
  version: 2.0.0
paths:
  /users:
    get:
      summary: Get all users
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
components:
  schemas:
    User:
      type: object
      required:
        - email
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
