openapi: 3.0.0
info:
  title: Example API
  version: 1.1.0
paths:
  /users:
    get:
      summary: Get all users
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            description: Pagination offset
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Success
    post:
      summary: Create a product
      responses:
        '201':
          description: Created
  /orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: Success
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
          description: Optional phone number
    Order:
      type: object
      properties:
        id:
          type: string
        total:
          type: number

